from django.urls import path

from . import views

urlpatterns = [path("index.html", views.index, name="index"),	      
			path("PatientLogin.html", views.PatientLogin, name="PatientLogin"),
			path("DoctorLogin.html", views.DoctorLogin, name="DoctorLogin"),
			path("PatientSignup.html", views.PatientSignup, name="PatientSignup"),
			path("PatientSignupAction", views.PatientSignupAction, name="PatientSignupAction"),
			path("PatientLoginAction", views.PatientLoginAction, name="PatientLoginAction"),
			path("DoctorLoginAction", views.DoctorLoginAction, name="DoctorLoginAction"),
			path("AdminLogin.html", views.AdminLogin, name="AdminLogin"),
			path("AdminLoginAction", views.AdminLoginAction, name="AdminLoginAction"),
			path("AddDoctor.html", views.AddDoctor, name="AddDoctor"),
			path("AddDoctorAction", views.AddDoctorAction, name="AddDoctorAction"),
			path("ViewHospitalDetails", views.ViewHospitalDetails, name="ViewHospitalDetails"),
			path("ViewPatientReport", views.ViewPatientReport, name="ViewPatientReport"),
			path("Prescription", views.Prescription, name="Prescription"),
			path("PrescriptionAction", views.PrescriptionAction, name="PrescriptionAction"),
			path("ViewInsurance.html", views.ViewInsurance, name="ViewInsurance"),
			path("ViewPrescription", views.ViewPrescription, name="ViewPrescription"),
			path("UpdateTimeTable.html", views.UpdateTimeTable, name="UpdateTimeTable"),
			path("UpdateTimeTableAction", views.UpdateTimeTableAction, name="UpdateTimeTableAction"),
			path("ScheduleMeetings.html", views.ScheduleMeetings, name="ScheduleMeetings"),
			path("ScheduleMeetingsAction", views.ScheduleMeetingsAction, name="ScheduleMeetingsAction"),
			path("OnlineAppointments.html", views.OnlineAppointments, name="OnlineAppointments"),
			path("OnlineAppointmentsAction", views.OnlineAppointmentsAction, name="OnlineAppointmentsAction"),
			path("ViewPatientPrescription", views.ViewPatientPrescription, name="ViewPatientPrescription"),
			path("ViewTimeTable", views.ViewTimeTable, name="ViewTimeTable"),
			path("ViewMeetings", views.ViewMeetings, name="ViewMeetings"),
			path("ViewAppointments", views.ViewAppointments, name="ViewAppointments"),
			path("Chat.html", views.Chat, name="Chat"),
			path("ChatData", views.ChatData, name="ChatData"),
]